const routes = {
    admin: [
        "/",
        "/citas",
        "/pagos",
        "/personal",
        "/rafam/comercios",
        "/rafam/comercio/:param",
        "/rafam/comercios/:param",
        "/rafam/inmuebles",
        "/rafam/inmueble/:param",
        "/rafam/rodados",
        "/rafam/rodado/:rodado",
        "/salud/emergencias",
        "/salud/cartilla",
        "/salud/cartilla/medicos/:param",
        "/salud/cartilla/centros/:param",
        "/salud/internacion",
        "/salud/turnos",
        "/gestion/reclamos",
        "/gestion/campañas",
        "/acceso-denegado",
    ],
    tasas: [
        "/",
        "/personal",
        "/rafam/comercios",
        "/rafam/comercio/:param",
        "/rafam/comercios/:param",
        "/rafam/inmuebles",
        "/rafam/inmueble/:param",
        "/rafam/rodados",
        "/rafam/rodado/:param",
        "/acceso-denegado",
    ],
};
export default routes;
